version: '3.8'
services:
  postgres:
    image: postgres:17.2
    container_name: contract_work_db
    environment:
      POSTGRES_DB: contract_work
      POSTGRES_USER: contract_user
      POSTGRES_PASSWORD: contract_pass
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: